### ISSUE TITLE
top kek

### ISSUE THREAD

**Issue by x4e** [THEREALWWEFAN231/wwe-s-auto-32k#1]

**Comment by THEREALWWEFAN231** [comment]
![image](https://user-images.githubusercontent.com/21975901/63464792-d72dbe00-c414-11e9-9183-dbfedadb6c5d.png)

**Comment by x4e** [comment]
https://github.com/THEREALWWEFAN231/wwe-s-auto-32k/blob/master/Auto32kModule.java#L117 Line 117 literally made me rofl hahahaha

Pretty ironic how in the Rhack leak you wrote

> Skidded so badly that there is Minecraft.getMinecraft(); spreaded randomly, not even being used, skidded from decompiled client, he skidded it and dident even look at the source/care to remove it.

Yet youve literally managed to fit 1 Minecraft.getMinecraft() every 3 lines haha (73 in total) https://imgur.com/a/qYU1bfL and **6** (yes that's right **6**) Minecraft.getMinecrafts into a single if statement https://i.imgur.com/dASH8xH.png.

Thank you for giving me some quality humour

**Comment by THEREALWWEFAN231** [comment]
> https://github.com/THEREALWWEFAN231/wwe-s-auto-32k/blob/master/Auto32kModule.java#L117 Line 117 literally made me rofl hahahaha
> 
> Pretty ironic how in the Rhack leak you wrote
> 
> > Skidded so badly that there is Minecraft.getMinecraft(); spreaded randomly, not even being used, skidded from decompiled client, he skidded it and dident even look at the source/care to remove it.
> 
> Yet youve literally managed to fit 1 Minecraft.getMinecraft() every 3 lines haha (73 in total) https://imgur.com/a/qYU1bfL and **6** (yes that's right **6**) Minecraft.getMinecrafts into a single if statement https://i.imgur.com/dASH8xH.png.
> 
> Thank you for giving me some quality humour

Ahhh very cool, this was the actual code when I wrote it for wwe, https://pastebin.com/Q2LU1e2a , cps isn't there yet, then I ported it to a forge mod, and I dident copy the wrapper class instead, i replaced Wrapper.mc, with Minecraft.getMinecraft().

And what I was talking about with rh is something like this
Minecraft.getMinecraft();
Minecraft.getMinecraft().player.something();

Stop being so stupid

**Comment by THEREALWWEFAN231** [comment]
Stop trying to act like a cool kid, you had it only place at the mouse cursor

**Comment by x4e** [comment]
> Ahhh very cool, this was the actual code when I wrote it for wwe, https://pastebin.com/Q2LU1e2a , cps isn't there yet, then I ported it to a forge mod, and I dident copy the wrapper class instead, i replaced Wrapper.mc, with Minecraft.getMinecraft().

Oh yeah, as I guessed theres still the commented out code, hardcoded variables and gigantic if statement:
```Java
if (Wrapper.mc.player.getDistance(blockPos.getX(), blockPos.getY(), blockPos.getZ()) < closestBlockPosDistance && Wrapper.mc.world.getEntitiesWithinAABB(Entity.class, new AxisAlignedBB(blockPos.add(0, 1, 0)), predicate).isEmpty() && !(Wrapper.mc.world.getBlockState(blockPos.down()).getBlock() instanceof BlockAir) && Wrapper.mc.world.getBlockState(blockPos).getBlock() instanceof BlockAir && Wrapper.mc.world.getBlockState(blockPos.up()).getBlock() instanceof BlockAir && Wrapper.mc.world.getBlockState(blockPos.up().up()).getBlock() instanceof BlockAir) {
                    closestBlockPosDistance = Wrapper.mc.player.getDistance(blockPos.getX(), blockPos.getY(), blockPos.getZ());
                    closestBlockPos = blockPos;
```

> And what I was talking about with rh is something like this
> Minecraft.getMinecraft();
> Minecraft.getMinecraft().player.something();

Oh you mean the thing that you use 53 times?
![weird](https://i.imgur.com/HZ9lPey.png)

**Comment by THEREALWWEFAN231** [comment]
Holy sh** you are stupid, o god help me

**Comment by x4e** [comment]
What exactly am I getting wrong here, I’ll be happy to correct any mistakes. All I can see is a single file filled with over 70 Minecraft.getMinecrafts made by the same guy complaining about John doing the same thing. 

Guessing that John learnt to code that way from using your code base.

But oh don’t worry cause in the wwe version he switched it to Wrapper.mc instead of Minecraft.getMinecraft()!!! Crisis averted guys!

**Comment by THEREALWWEFAN231** [comment]
Yes indeed,  Crisis averted, there is no difference whats so ever from Wrapper.mc, and Minecraft.getMinecraft(), this isn't a direct copy from rusher hack but there was stuff like this in rusher hack(im talking about the blue), i have nothing wrong with the red, byside its being invoke statically when it should be invoked like Minecraft.getMinecraft(), I called out john for the random not being used Minecraft.getMinecraft();'s
![image](https://user-images.githubusercontent.com/21975901/63474536-6398aa80-c42e-11e9-9936-d555013938f1.png)

**Comment by x4e** [comment]
Also top kek on this:

> Stop trying to act like a cool kid, you had it only place at the mouse cursor
 
Oh no I’m such an idiot! I had it place somewhere that the user had selected as the optimum place for that situation! Damn it I should’ve just randomly chosen a space anywhere within a abitrary range no matter what the user wanted

**Comment by x4e** [comment]
Oh ok I get what you mean with the random Minecraft.getMinecraft()s without any use. Pretty bad. Although I’d imagine the compiler would remove them so they shouldn’t actually affect performance.

**Comment by THEREALWWEFAN231** [comment]
Im actually pretty sure the compiler wouldent remove them, i dont see it knowing weather or not something else is happening beside it returning a instance, for example 
public Minecraft getMinecraft(){
System.out.println("this happened"); 
return someInstance;
}
and the random minecrafts come from some decompiler, but then theres no reason for them to be in a direct source file from the "creator of the client"(unless of corse its skidded)
We done here?

**Comment by x4e** [comment]
Yes your right as it’s a method not a field. But yeah of course it’s skidded. You can see in parts of the rhack source unused functions, mismatched indent levels and different code styles so it’s very obvious. 

Btw you should write your code a bit nicer. For example with the if statement separate it into different lines.

**Comment by THEREALWWEFAN231** [comment]
I know some people like if statements going onto different lines but I have eclipse to set up so when I organize it, they stay on one like, I hate the way it looks going down 5x lines, although I can lie, that one very long line is pretty bad.

**Comment by Tigermouthbear** [comment]
Lol, he added an mc variable. Why didn't you do that in the first place?

**Comment by THEREALWWEFAN231** [comment]
> Lol, he added an mc variable. Why didn't you do that in the first place?

I dident, unrootexe did, I don't have time to change it even though it doesnt take that long, and i dident do that in the first place because it makes no difference whats so ever, it just looks nicer, no difference = no need

**Comment by x4e** [comment]
![as](https://i.imgur.com/Y3I7q6m.png)

Just use flags like Minecraft do. Makes it much easier to read.
