### ISSUE TITLE
1 tap on 2b2t is impossible due to speed of sword and - not working

### ISSUE THREAD

**Issue by KILLSA** [THEREALWWEFAN231/wwe-s-auto-32k#3]
Everything is beautifully done and no problems with the client besides the 1 tap or a way to disable your aura and let me put my aura on. Anything would help thanks

**Comment by THEREALWWEFAN231** [comment]
In the newest release, there is the ability to turn kill aura off.

**Comment by THEREALWWEFAN231** [comment]
Its actually fixed now..

**Comment by x4e** [comment]
@KILLSA 

![a](https://i.imgur.com/K0etH5M.png)
![b](https://i.imgur.com/eLeWSR7.png)
hmm
