### ISSUE TITLE
 I can't use it

### ISSUE THREAD

**Issue by kevin0111** [THEREALWWEFAN231/wwe-s-auto-32k#6]
I downloaded it and also lost it to the mod qualification folder. Why is there no game?

**Comment by THEREALWWEFAN231** [comment]
... go to releases, download the newest jar, and put it in your mods folder

**Comment by kevin0111** [comment]
What is the newest jar?

**Comment by THEREALWWEFAN231** [comment]
https://github.com/THEREALWWEFAN231/wwe-s-auto-32k/releases/download/0.1.2/wwe.s.auto.32k.jar

**Comment by kevin0111** [comment]
I can use it, thank you very much.

**Comment by Square365H** [comment]
no
